name: todoapp

services:
  web:
    image: jr_module4
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: alexprokopiev
    ports:
      - "5433:5432"